# Generated by Django 3.1.2 on 2020-10-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_category_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploader',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
