# Generated by Django 3.1.2 on 2020-10-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_uploader_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
