# Generated by Django 3.1.2 on 2020-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20201012_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(blank=True, upload_to='bazuu/'),
        ),
    ]
